/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const platformerPlayerShader: CompiledShader<{ aPosition: 'vec3'; aUv: 'vec2' }, { iState: 'vec4' }, { uCamera: 'vec4'; uAtlas: 'sampler2D'; uCutoff: 'float'; uAtlasGeom: 'vec4'; uTime: 'float'; uPlayer: 'vec3'; uFrames: 'vec2' }> = {
  vertexSrc: `#version 300 es
layout(location = 0) in vec3 aPosition;
layout(location = 1) in vec2 aUv;
layout(location = 2) in vec4 iState;
uniform vec4 uCamera;
uniform vec4 uAtlasGeom;
uniform float uTime;
uniform vec3 uPlayer;
uniform vec2 uFrames;
out vec2 vUv;
vec4 tileRect(float tile, vec4 geom) {
  float du = 1.0 / geom.x;
  float dv = 1.0 / geom.y;
  float col = mod(tile, geom.x);
  float row = floor(tile / geom.x);
  return vec4(col * du + geom.z, 1.0 - (row + 1.0) * dv + geom.w, du - geom.z * 2.0, dv - geom.w * 2.0);
}
vec4 toClip(vec3 world, vec4 cam) {
  return vec4((world.x - cam.x) / cam.z, (world.y - cam.y) / cam.w, -world.z, 1.0);
}
void main() {
  float airborne = 1.0 - step(0.5, iState.w);
  float running = step(1.5, iState.w);
  float cycle = mod(floor(uTime * uPlayer.z), 2.0);
  float tile = mix(uFrames.x, uFrames.y, airborne + running * cycle);
  vec4 rect = tileRect(tile, uAtlasGeom);
  vUv = rect.xy + aUv * rect.zw;
  float width = uPlayer.x * iState.z;
  gl_Position = toClip(vec3(iState.x + aPosition.x * width, iState.y + aPosition.y * uPlayer.x, uPlayer.y), uCamera);
}
`,
  fragmentSrc: `#version 300 es
precision highp float;
uniform sampler2D uAtlas;
uniform float uCutoff;
in vec2 vUv;
out vec4 fragColor;
void main() {
  vec4 texel = texture(uAtlas, vUv);
  if (texel.w < uCutoff) {
    discard;
  }
  fragColor = vec4(texel.xyz, 1.0);
}
`,
  wgslSrc: `struct BmUniforms {
  uCamera : vec4f,
  uCutoff : f32,
  uAtlasGeom : vec4f,
  uTime : f32,
  uPlayer : vec3f,
  uFrames : vec2f,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
@group(0) @binding(1) var uAtlas : texture_2d<f32>;
@group(0) @binding(2) var uAtlas_sampler : sampler;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aUv : vec2f,
  @location(2) iState : vec4f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vUv : vec2f,
}
fn tileRect(tile : f32, geom : vec4f) -> vec4f {
  let du = 1.0 / geom.x;
  let dv = 1.0 / geom.y;
  let col = ((tile) - (geom.x) * floor((tile) / (geom.x)));
  let row = floor(tile / geom.x);
  return vec4f(col * du + geom.z, 1.0 - (row + 1.0) * dv + geom.w, du - geom.z * 2.0, dv - geom.w * 2.0);
}
fn toClip(world : vec3f, cam : vec4f) -> vec4f {
  return vec4f((world.x - cam.x) / cam.z, (world.y - cam.y) / cam.w, -world.z, 1.0);
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  let airborne = 1.0 - step(0.5, bm_in.iState.w);
  let running = step(1.5, bm_in.iState.w);
  let cycle = ((floor(bm_u.uTime * bm_u.uPlayer.z)) - (2.0) * floor((floor(bm_u.uTime * bm_u.uPlayer.z)) / (2.0)));
  let tile = mix(bm_u.uFrames.x, bm_u.uFrames.y, airborne + running * cycle);
  let rect = tileRect(tile, bm_u.uAtlasGeom);
  bm_out.vUv = rect.xy + bm_in.aUv * rect.zw;
  let width = bm_u.uPlayer.x * bm_in.iState.z;
  bm_out.bm_position = toClip(vec3f(bm_in.iState.x + bm_in.aPosition.x * width, bm_in.iState.y + bm_in.aPosition.y * bm_u.uPlayer.x, bm_u.uPlayer.y), bm_u.uCamera);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let texel = textureSample(uAtlas, uAtlas_sampler, bm_in.vUv);
  if (texel.w < bm_u.uCutoff) {
    discard;
  }
  return vec4f(texel.xyz, 1.0);
}
`,
  attributes: { aPosition: 'vec3', aUv: 'vec2' },
  instanceAttributes: { iState: 'vec4' },
  uniforms: { uCamera: 'vec4', uAtlas: 'sampler2D', uCutoff: 'float', uAtlasGeom: 'vec4', uTime: 'float', uPlayer: 'vec3', uFrames: 'vec2' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aUv","type":"vec2","location":1,"size":2,"divisor":0},{"name":"iState","type":"vec4","location":2,"size":4,"divisor":1}],"uniforms":[{"name":"uCamera","type":"vec4","kind":"4fv","size":4,"offset":0},{"name":"uAtlas","type":"sampler2D","kind":"1i","size":1,"unit":0,"textureBinding":1,"samplerBinding":2},{"name":"uCutoff","type":"float","kind":"1f","size":1,"offset":16},{"name":"uAtlasGeom","type":"vec4","kind":"4fv","size":4,"offset":32},{"name":"uTime","type":"float","kind":"1f","size":1,"offset":48},{"name":"uPlayer","type":"vec3","kind":"3fv","size":3,"offset":64},{"name":"uFrames","type":"vec2","kind":"2fv","size":2,"offset":80}],"uniformBlockSize":96},
};

export default platformerPlayerShader;
