/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const platformerParallaxShader: CompiledShader<{ aPosition: 'vec3'; aUv: 'vec2' }, { iSlot: 'vec2' }, { uAtlas: 'sampler2D'; uCutoff: 'float'; uAtlasGeom: 'vec4'; uCamera: 'vec4'; uBand: 'vec4'; uTiles: 'vec3' }> = {
  vertexSrc: `#version 300 es
layout(location = 0) in vec3 aPosition;
layout(location = 1) in vec2 aUv;
layout(location = 2) in vec2 iSlot;
uniform vec4 uAtlasGeom;
uniform vec4 uCamera;
uniform vec4 uBand;
uniform vec3 uTiles;
out vec2 vUv;
vec4 tileRect(float tile, vec4 geom) {
  float du = 1.0 / geom.x;
  float dv = 1.0 / geom.y;
  float col = mod(tile, geom.x);
  float row = floor(tile / geom.x);
  return vec4(col * du + geom.z, 1.0 - (row + 1.0) * dv + geom.w, du - geom.z * 2.0, dv - geom.w * 2.0);
}
vec4 toClip(vec3 world, vec4 cam) {
  return vec4((world.x - cam.x) / cam.z, (world.y - cam.y) / cam.w, -world.z, 1.0);
}
void main() {
  float band = uBand.x;
  float drift = uCamera.x * uBand.z;
  float anchor = uCamera.x - drift;
  float first = floor((anchor - uCamera.z) / band) - 1.0;
  float strip = first + iSlot.x;
  float tier = iSlot.y;
  float tile = mix(uTiles.x + mod(abs(strip), uTiles.y), uTiles.z, tier);
  vec4 rect = tileRect(tile, uAtlasGeom);
  vUv = rect.xy + aUv * rect.zw;
  float cx = strip * band + drift;
  float cy = uBand.y - band * tier;
  gl_Position = toClip(vec3(cx + aPosition.x * band, cy + aPosition.y * band, uBand.w), uCamera);
}
`,
  fragmentSrc: `#version 300 es
precision highp float;
uniform sampler2D uAtlas;
uniform float uCutoff;
in vec2 vUv;
out vec4 fragColor;
void main() {
  vec4 texel = texture(uAtlas, vUv);
  if (texel.w < uCutoff) {
    discard;
  }
  fragColor = vec4(texel.xyz, 1.0);
}
`,
  wgslSrc: `struct BmUniforms {
  uCutoff : f32,
  uAtlasGeom : vec4f,
  uCamera : vec4f,
  uBand : vec4f,
  uTiles : vec3f,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
@group(0) @binding(1) var uAtlas : texture_2d<f32>;
@group(0) @binding(2) var uAtlas_sampler : sampler;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aUv : vec2f,
  @location(2) iSlot : vec2f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vUv : vec2f,
}
fn tileRect(tile : f32, geom : vec4f) -> vec4f {
  let du = 1.0 / geom.x;
  let dv = 1.0 / geom.y;
  let col = ((tile) - (geom.x) * floor((tile) / (geom.x)));
  let row = floor(tile / geom.x);
  return vec4f(col * du + geom.z, 1.0 - (row + 1.0) * dv + geom.w, du - geom.z * 2.0, dv - geom.w * 2.0);
}
fn toClip(world : vec3f, cam : vec4f) -> vec4f {
  return vec4f((world.x - cam.x) / cam.z, (world.y - cam.y) / cam.w, -world.z, 1.0);
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  let band = bm_u.uBand.x;
  let drift = bm_u.uCamera.x * bm_u.uBand.z;
  let anchor = bm_u.uCamera.x - drift;
  let first = floor((anchor - bm_u.uCamera.z) / band) - 1.0;
  let strip = first + bm_in.iSlot.x;
  let tier = bm_in.iSlot.y;
  let tile = mix(bm_u.uTiles.x + ((abs(strip)) - (bm_u.uTiles.y) * floor((abs(strip)) / (bm_u.uTiles.y))), bm_u.uTiles.z, tier);
  let rect = tileRect(tile, bm_u.uAtlasGeom);
  bm_out.vUv = rect.xy + bm_in.aUv * rect.zw;
  let cx = strip * band + drift;
  let cy = bm_u.uBand.y - band * tier;
  bm_out.bm_position = toClip(vec3f(cx + bm_in.aPosition.x * band, cy + bm_in.aPosition.y * band, bm_u.uBand.w), bm_u.uCamera);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let texel = textureSample(uAtlas, uAtlas_sampler, bm_in.vUv);
  if (texel.w < bm_u.uCutoff) {
    discard;
  }
  return vec4f(texel.xyz, 1.0);
}
`,
  attributes: { aPosition: 'vec3', aUv: 'vec2' },
  instanceAttributes: { iSlot: 'vec2' },
  uniforms: { uAtlas: 'sampler2D', uCutoff: 'float', uAtlasGeom: 'vec4', uCamera: 'vec4', uBand: 'vec4', uTiles: 'vec3' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aUv","type":"vec2","location":1,"size":2,"divisor":0},{"name":"iSlot","type":"vec2","location":2,"size":2,"divisor":1}],"uniforms":[{"name":"uAtlas","type":"sampler2D","kind":"1i","size":1,"unit":0,"textureBinding":1,"samplerBinding":2},{"name":"uCutoff","type":"float","kind":"1f","size":1,"offset":0},{"name":"uAtlasGeom","type":"vec4","kind":"4fv","size":4,"offset":16},{"name":"uCamera","type":"vec4","kind":"4fv","size":4,"offset":32},{"name":"uBand","type":"vec4","kind":"4fv","size":4,"offset":48},{"name":"uTiles","type":"vec3","kind":"3fv","size":3,"offset":64}],"uniformBlockSize":80},
};

export default platformerParallaxShader;
