/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const platformerPropsShader: CompiledShader<{ aPosition: 'vec3'; aUv: 'vec2' }, { iCenter: 'vec3'; iStamp: 'vec4'; iAlive: 'float' }, { uCamera: 'vec4'; uAtlas: 'sampler2D'; uCutoff: 'float'; uAtlasGeom: 'vec4'; uTime: 'float'; uBob: 'vec2'; uFlag: 'vec3'; uCoinTint: 'vec3' }> = {
  vertexSrc: `#version 300 es
layout(location = 0) in vec3 aPosition;
layout(location = 1) in vec2 aUv;
layout(location = 2) in vec3 iCenter;
layout(location = 3) in vec4 iStamp;
layout(location = 4) in float iAlive;
uniform vec4 uCamera;
uniform vec4 uAtlasGeom;
uniform float uTime;
uniform vec2 uBob;
uniform vec3 uFlag;
uniform vec3 uCoinTint;
out vec2 vUv;
out vec3 vTint;
vec4 tileRect(float tile, vec4 geom) {
  float du = 1.0 / geom.x;
  float dv = 1.0 / geom.y;
  float col = mod(tile, geom.x);
  float row = floor(tile / geom.x);
  return vec4(col * du + geom.z, 1.0 - (row + 1.0) * dv + geom.w, du - geom.z * 2.0, dv - geom.w * 2.0);
}
vec4 toClip(vec3 world, vec4 cam) {
  return vec4((world.x - cam.x) / cam.z, (world.y - cam.y) / cam.w, -world.z, 1.0);
}
void main() {
  float isFlag = iStamp.w;
  float bob = sin(uTime * uBob.x + iCenter.x) * uBob.y * (1.0 - isFlag);
  float tile = mix(iStamp.x, uFlag.x + mod(floor(uTime * uFlag.y), uFlag.z), isFlag);
  vec4 rect = tileRect(tile, uAtlasGeom);
  vUv = rect.xy + aUv * rect.zw;
  vTint = mix(uCoinTint, vec3(1.0, 1.0, 1.0), isFlag);
  vec4 clip = toClip(vec3(iCenter.x + aPosition.x * iStamp.y, iCenter.y + bob + aPosition.y * iStamp.z, iCenter.z), uCamera);
  if (iAlive < 0.5) {
    clip = vec4(2.0, 2.0, 2.0, 1.0);
  }
  gl_Position = clip;
}
`,
  fragmentSrc: `#version 300 es
precision highp float;
uniform sampler2D uAtlas;
uniform float uCutoff;
in vec2 vUv;
in vec3 vTint;
out vec4 fragColor;
void main() {
  vec4 texel = texture(uAtlas, vUv);
  if (texel.w < uCutoff) {
    discard;
  }
  fragColor = vec4(texel.xyz * vTint, 1.0);
}
`,
  wgslSrc: `struct BmUniforms {
  uCamera : vec4f,
  uCutoff : f32,
  uAtlasGeom : vec4f,
  uTime : f32,
  uBob : vec2f,
  uFlag : vec3f,
  uCoinTint : vec3f,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
@group(0) @binding(1) var uAtlas : texture_2d<f32>;
@group(0) @binding(2) var uAtlas_sampler : sampler;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aUv : vec2f,
  @location(2) iCenter : vec3f,
  @location(3) iStamp : vec4f,
  @location(4) iAlive : f32,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vUv : vec2f,
  @location(1) vTint : vec3f,
}
fn tileRect(tile : f32, geom : vec4f) -> vec4f {
  let du = 1.0 / geom.x;
  let dv = 1.0 / geom.y;
  let col = ((tile) - (geom.x) * floor((tile) / (geom.x)));
  let row = floor(tile / geom.x);
  return vec4f(col * du + geom.z, 1.0 - (row + 1.0) * dv + geom.w, du - geom.z * 2.0, dv - geom.w * 2.0);
}
fn toClip(world : vec3f, cam : vec4f) -> vec4f {
  return vec4f((world.x - cam.x) / cam.z, (world.y - cam.y) / cam.w, -world.z, 1.0);
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  let isFlag = bm_in.iStamp.w;
  let bob = sin(bm_u.uTime * bm_u.uBob.x + bm_in.iCenter.x) * bm_u.uBob.y * (1.0 - isFlag);
  let tile = mix(bm_in.iStamp.x, bm_u.uFlag.x + ((floor(bm_u.uTime * bm_u.uFlag.y)) - (bm_u.uFlag.z) * floor((floor(bm_u.uTime * bm_u.uFlag.y)) / (bm_u.uFlag.z))), isFlag);
  let rect = tileRect(tile, bm_u.uAtlasGeom);
  bm_out.vUv = rect.xy + bm_in.aUv * rect.zw;
  bm_out.vTint = mix(bm_u.uCoinTint, vec3f(1.0, 1.0, 1.0), isFlag);
  var clip = toClip(vec3f(bm_in.iCenter.x + bm_in.aPosition.x * bm_in.iStamp.y, bm_in.iCenter.y + bob + bm_in.aPosition.y * bm_in.iStamp.z, bm_in.iCenter.z), bm_u.uCamera);
  if (bm_in.iAlive < 0.5) {
    clip = vec4f(2.0, 2.0, 2.0, 1.0);
  }
  bm_out.bm_position = clip;
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let texel = textureSample(uAtlas, uAtlas_sampler, bm_in.vUv);
  if (texel.w < bm_u.uCutoff) {
    discard;
  }
  return vec4f(texel.xyz * bm_in.vTint, 1.0);
}
`,
  attributes: { aPosition: 'vec3', aUv: 'vec2' },
  instanceAttributes: { iCenter: 'vec3', iStamp: 'vec4', iAlive: 'float' },
  uniforms: { uCamera: 'vec4', uAtlas: 'sampler2D', uCutoff: 'float', uAtlasGeom: 'vec4', uTime: 'float', uBob: 'vec2', uFlag: 'vec3', uCoinTint: 'vec3' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aUv","type":"vec2","location":1,"size":2,"divisor":0},{"name":"iCenter","type":"vec3","location":2,"size":3,"divisor":1},{"name":"iStamp","type":"vec4","location":3,"size":4,"divisor":1},{"name":"iAlive","type":"float","location":4,"size":1,"divisor":1}],"uniforms":[{"name":"uCamera","type":"vec4","kind":"4fv","size":4,"offset":0},{"name":"uAtlas","type":"sampler2D","kind":"1i","size":1,"unit":0,"textureBinding":1,"samplerBinding":2},{"name":"uCutoff","type":"float","kind":"1f","size":1,"offset":16},{"name":"uAtlasGeom","type":"vec4","kind":"4fv","size":4,"offset":32},{"name":"uTime","type":"float","kind":"1f","size":1,"offset":48},{"name":"uBob","type":"vec2","kind":"2fv","size":2,"offset":56},{"name":"uFlag","type":"vec3","kind":"3fv","size":3,"offset":64},{"name":"uCoinTint","type":"vec3","kind":"3fv","size":3,"offset":80}],"uniformBlockSize":96},
};

export default platformerPropsShader;
