/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const platformerWalkersShader: CompiledShader<{ aPosition: 'vec3'; aUv: 'vec2' }, { iPatrol: 'vec4'; iTrait: 'vec4'; iUvRect: 'vec4' }, { uCamera: 'vec4'; uAtlas: 'sampler2D'; uCutoff: 'float'; uTime: 'float' }> = {
  vertexSrc: `#version 300 es
layout(location = 0) in vec3 aPosition;
layout(location = 1) in vec2 aUv;
layout(location = 2) in vec4 iPatrol;
layout(location = 3) in vec4 iTrait;
layout(location = 4) in vec4 iUvRect;
uniform vec4 uCamera;
uniform float uTime;
out vec2 vUv;
vec4 toClip(vec3 world, vec4 cam) {
  return vec4((world.x - cam.x) / cam.z, (world.y - cam.y) / cam.w, -world.z, 1.0);
}
void main() {
  float w = uTime * iPatrol.w + iTrait.x;
  float t = (sin(w) + 1.0) * 0.5;
  float cx = iPatrol.x + (iPatrol.y - iPatrol.x) * t;
  float facing = step(0.0, cos(w)) * 2.0 - 1.0;
  vUv = iUvRect.xy + aUv * iUvRect.zw;
  gl_Position = toClip(vec3(cx + aPosition.x * iTrait.y * facing, iPatrol.z + aPosition.y * iTrait.z, iTrait.w), uCamera);
}
`,
  fragmentSrc: `#version 300 es
precision highp float;
uniform sampler2D uAtlas;
uniform float uCutoff;
in vec2 vUv;
out vec4 fragColor;
void main() {
  vec4 texel = texture(uAtlas, vUv);
  if (texel.w < uCutoff) {
    discard;
  }
  fragColor = vec4(texel.xyz, 1.0);
}
`,
  wgslSrc: `struct BmUniforms {
  uCamera : vec4f,
  uCutoff : f32,
  uTime : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
@group(0) @binding(1) var uAtlas : texture_2d<f32>;
@group(0) @binding(2) var uAtlas_sampler : sampler;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aUv : vec2f,
  @location(2) iPatrol : vec4f,
  @location(3) iTrait : vec4f,
  @location(4) iUvRect : vec4f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vUv : vec2f,
}
fn toClip(world : vec3f, cam : vec4f) -> vec4f {
  return vec4f((world.x - cam.x) / cam.z, (world.y - cam.y) / cam.w, -world.z, 1.0);
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  let w = bm_u.uTime * bm_in.iPatrol.w + bm_in.iTrait.x;
  let t = (sin(w) + 1.0) * 0.5;
  let cx = bm_in.iPatrol.x + (bm_in.iPatrol.y - bm_in.iPatrol.x) * t;
  let facing = step(0.0, cos(w)) * 2.0 - 1.0;
  bm_out.vUv = bm_in.iUvRect.xy + bm_in.aUv * bm_in.iUvRect.zw;
  bm_out.bm_position = toClip(vec3f(cx + bm_in.aPosition.x * bm_in.iTrait.y * facing, bm_in.iPatrol.z + bm_in.aPosition.y * bm_in.iTrait.z, bm_in.iTrait.w), bm_u.uCamera);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let texel = textureSample(uAtlas, uAtlas_sampler, bm_in.vUv);
  if (texel.w < bm_u.uCutoff) {
    discard;
  }
  return vec4f(texel.xyz, 1.0);
}
`,
  attributes: { aPosition: 'vec3', aUv: 'vec2' },
  instanceAttributes: { iPatrol: 'vec4', iTrait: 'vec4', iUvRect: 'vec4' },
  uniforms: { uCamera: 'vec4', uAtlas: 'sampler2D', uCutoff: 'float', uTime: 'float' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aUv","type":"vec2","location":1,"size":2,"divisor":0},{"name":"iPatrol","type":"vec4","location":2,"size":4,"divisor":1},{"name":"iTrait","type":"vec4","location":3,"size":4,"divisor":1},{"name":"iUvRect","type":"vec4","location":4,"size":4,"divisor":1}],"uniforms":[{"name":"uCamera","type":"vec4","kind":"4fv","size":4,"offset":0},{"name":"uAtlas","type":"sampler2D","kind":"1i","size":1,"unit":0,"textureBinding":1,"samplerBinding":2},{"name":"uCutoff","type":"float","kind":"1f","size":1,"offset":16},{"name":"uTime","type":"float","kind":"1f","size":1,"offset":20}],"uniformBlockSize":32},
};

export default platformerWalkersShader;
