/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const platformerTerrainShader: CompiledShader<{ aPosition: 'vec3'; aUv: 'vec2' }, { iCell: 'vec2' }, { uCamera: 'vec4'; uAtlas: 'sampler2D'; uCutoff: 'float'; uAtlasGeom: 'vec4'; uLevel: 'sampler2D'; uLevelSize: 'vec2'; uRuns: 'vec4'; uParams: 'vec4' }> = {
  vertexSrc: `#version 300 es
layout(location = 0) in vec3 aPosition;
layout(location = 1) in vec2 aUv;
layout(location = 2) in vec2 iCell;
uniform vec4 uCamera;
uniform vec4 uAtlasGeom;
uniform sampler2D uLevel;
uniform vec2 uLevelSize;
uniform vec4 uRuns;
uniform vec4 uParams;
out vec2 vUv;
vec2 columnUv(float col, float width) {
  return vec2((col + 0.5) / width, 0.5);
}
float byteOf(float channel) {
  return floor(channel * 255.0 + 0.5);
}
vec4 tileRect(float tile, vec4 geom) {
  float du = 1.0 / geom.x;
  float dv = 1.0 / geom.y;
  float col = mod(tile, geom.x);
  float row = floor(tile / geom.x);
  return vec4(col * du + geom.z, 1.0 - (row + 1.0) * dv + geom.w, du - geom.z * 2.0, dv - geom.w * 2.0);
}
vec4 toClip(vec3 world, vec4 cam) {
  return vec4((world.x - cam.x) / cam.z, (world.y - cam.y) / cam.w, -world.z, 1.0);
}
void main() {
  float col = iCell.x;
  float row = iCell.y;
  vec4 cell = texture(uLevel, columnUv(col, uLevelSize.x));
  vec4 left = texture(uLevel, columnUv(col - 1.0, uLevelSize.x));
  vec4 right = texture(uLevel, columnUv(col + 1.0, uLevelSize.x));
  float h = byteOf(cell.x) - 1.0;
  float hLeft = byteOf(left.x) - 1.0;
  float hRight = byteOf(right.x) - 1.0;
  float hasLeft = step(0.0, col - 1.0);
  float hasRight = step(col + 1.0, uLevelSize.x - 1.0);
  float filledLeft = hasLeft * step(0.0, hLeft) * step(row, hLeft);
  float filledRight = hasRight * step(0.0, hRight) * step(row, hRight);
  float openLeft = 1.0 - filledLeft;
  float openRight = 1.0 - filledRight;
  float variant = openLeft * (1.0 - openRight) + 3.0 * (1.0 - openLeft) * openRight + 2.0 * (1.0 - openLeft) * (1.0 - openRight);
  float isTop = 1.0 - step(0.5, abs(row - h));
  float isBottom = 1.0 - step(0.5, row);
  float isLone = isTop * isBottom;
  float base = uRuns.w * isLone + uRuns.x * isTop * (1.0 - isLone) + uRuns.z * (1.0 - isTop) * isBottom + uRuns.y * (1.0 - isTop) * (1.0 - isBottom);
  float platformRow = byteOf(cell.z) - 1.0;
  float isPlatform = step(0.0, platformRow) * (1.0 - step(0.5, abs(row - platformRow)));
  float isDecor = 1.0 - step(0.5, abs(row - uParams.y));
  float decorTile = byteOf(cell.y);
  float tile = mix(mix(base + variant, uParams.x, isPlatform), decorTile, isDecor);
  vec4 rect = tileRect(tile, uAtlasGeom);
  vUv = rect.xy + aUv * rect.zw;
  float cy = mix(row + 0.5, h + 1.5, isDecor);
  float z = mix(uParams.z, uParams.w, isDecor);
  vec3 world = vec3(col + 0.5 + aPosition.x, cy + aPosition.y, z);
  float hasTile = max(step(0.0, h) * step(row, h), isPlatform);
  float alive = mix(hasTile, step(0.5, decorTile), isDecor);
  vec4 clip = toClip(world, uCamera);
  if (alive < 0.5) {
    clip = vec4(2.0, 2.0, 2.0, 1.0);
  }
  gl_Position = clip;
}
`,
  fragmentSrc: `#version 300 es
precision highp float;
uniform sampler2D uAtlas;
uniform float uCutoff;
in vec2 vUv;
out vec4 fragColor;
void main() {
  vec4 texel = texture(uAtlas, vUv);
  if (texel.w < uCutoff) {
    discard;
  }
  fragColor = vec4(texel.xyz, 1.0);
}
`,
  wgslSrc: `struct BmUniforms {
  uCamera : vec4f,
  uCutoff : f32,
  uAtlasGeom : vec4f,
  uLevelSize : vec2f,
  uRuns : vec4f,
  uParams : vec4f,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
@group(0) @binding(1) var uAtlas : texture_2d<f32>;
@group(0) @binding(2) var uAtlas_sampler : sampler;
@group(0) @binding(3) var uLevel : texture_2d<f32>;
@group(0) @binding(4) var uLevel_sampler : sampler;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aUv : vec2f,
  @location(2) iCell : vec2f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vUv : vec2f,
}
fn columnUv(col : f32, width : f32) -> vec2f {
  return vec2f((col + 0.5) / width, 0.5);
}
fn byteOf(channel : f32) -> f32 {
  return floor(channel * 255.0 + 0.5);
}
fn tileRect(tile : f32, geom : vec4f) -> vec4f {
  let du = 1.0 / geom.x;
  let dv = 1.0 / geom.y;
  let col = ((tile) - (geom.x) * floor((tile) / (geom.x)));
  let row = floor(tile / geom.x);
  return vec4f(col * du + geom.z, 1.0 - (row + 1.0) * dv + geom.w, du - geom.z * 2.0, dv - geom.w * 2.0);
}
fn toClip(world : vec3f, cam : vec4f) -> vec4f {
  return vec4f((world.x - cam.x) / cam.z, (world.y - cam.y) / cam.w, -world.z, 1.0);
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  let col = bm_in.iCell.x;
  let row = bm_in.iCell.y;
  let cell = textureSampleLevel(uLevel, uLevel_sampler, columnUv(col, bm_u.uLevelSize.x), 0.0);
  let left = textureSampleLevel(uLevel, uLevel_sampler, columnUv(col - 1.0, bm_u.uLevelSize.x), 0.0);
  let right = textureSampleLevel(uLevel, uLevel_sampler, columnUv(col + 1.0, bm_u.uLevelSize.x), 0.0);
  let h = byteOf(cell.x) - 1.0;
  let hLeft = byteOf(left.x) - 1.0;
  let hRight = byteOf(right.x) - 1.0;
  let hasLeft = step(0.0, col - 1.0);
  let hasRight = step(col + 1.0, bm_u.uLevelSize.x - 1.0);
  let filledLeft = hasLeft * step(0.0, hLeft) * step(row, hLeft);
  let filledRight = hasRight * step(0.0, hRight) * step(row, hRight);
  let openLeft = 1.0 - filledLeft;
  let openRight = 1.0 - filledRight;
  let variant = openLeft * (1.0 - openRight) + 3.0 * (1.0 - openLeft) * openRight + 2.0 * (1.0 - openLeft) * (1.0 - openRight);
  let isTop = 1.0 - step(0.5, abs(row - h));
  let isBottom = 1.0 - step(0.5, row);
  let isLone = isTop * isBottom;
  let base = bm_u.uRuns.w * isLone + bm_u.uRuns.x * isTop * (1.0 - isLone) + bm_u.uRuns.z * (1.0 - isTop) * isBottom + bm_u.uRuns.y * (1.0 - isTop) * (1.0 - isBottom);
  let platformRow = byteOf(cell.z) - 1.0;
  let isPlatform = step(0.0, platformRow) * (1.0 - step(0.5, abs(row - platformRow)));
  let isDecor = 1.0 - step(0.5, abs(row - bm_u.uParams.y));
  let decorTile = byteOf(cell.y);
  let tile = mix(mix(base + variant, bm_u.uParams.x, isPlatform), decorTile, isDecor);
  let rect = tileRect(tile, bm_u.uAtlasGeom);
  bm_out.vUv = rect.xy + bm_in.aUv * rect.zw;
  let cy = mix(row + 0.5, h + 1.5, isDecor);
  let z = mix(bm_u.uParams.z, bm_u.uParams.w, isDecor);
  let world = vec3f(col + 0.5 + bm_in.aPosition.x, cy + bm_in.aPosition.y, z);
  let hasTile = max(step(0.0, h) * step(row, h), isPlatform);
  let alive = mix(hasTile, step(0.5, decorTile), isDecor);
  var clip = toClip(world, bm_u.uCamera);
  if (alive < 0.5) {
    clip = vec4f(2.0, 2.0, 2.0, 1.0);
  }
  bm_out.bm_position = clip;
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let texel = textureSample(uAtlas, uAtlas_sampler, bm_in.vUv);
  if (texel.w < bm_u.uCutoff) {
    discard;
  }
  return vec4f(texel.xyz, 1.0);
}
`,
  attributes: { aPosition: 'vec3', aUv: 'vec2' },
  instanceAttributes: { iCell: 'vec2' },
  uniforms: { uCamera: 'vec4', uAtlas: 'sampler2D', uCutoff: 'float', uAtlasGeom: 'vec4', uLevel: 'sampler2D', uLevelSize: 'vec2', uRuns: 'vec4', uParams: 'vec4' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aUv","type":"vec2","location":1,"size":2,"divisor":0},{"name":"iCell","type":"vec2","location":2,"size":2,"divisor":1}],"uniforms":[{"name":"uCamera","type":"vec4","kind":"4fv","size":4,"offset":0},{"name":"uAtlas","type":"sampler2D","kind":"1i","size":1,"unit":0,"textureBinding":1,"samplerBinding":2},{"name":"uCutoff","type":"float","kind":"1f","size":1,"offset":16},{"name":"uAtlasGeom","type":"vec4","kind":"4fv","size":4,"offset":32},{"name":"uLevel","type":"sampler2D","kind":"1i","size":1,"unit":1,"textureBinding":3,"samplerBinding":4},{"name":"uLevelSize","type":"vec2","kind":"2fv","size":2,"offset":48},{"name":"uRuns","type":"vec4","kind":"4fv","size":4,"offset":64},{"name":"uParams","type":"vec4","kind":"4fv","size":4,"offset":80}],"uniformBlockSize":96},
};

export default platformerTerrainShader;
