/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const topdownDungeonShader: CompiledShader<{ aPosition: 'vec3'; aUv: 'vec2' }, { iSlot: 'vec4'; iRect: 'vec4' }, { uViewProj: 'mat4'; uMap: 'sampler2D'; uMapSize: 'vec2'; uLight: 'sampler2D'; uAtlas: 'sampler2D'; uAtlasGrid: 'vec2'; uAtlasInset: 'vec2'; uTime: 'float'; uCutoff: 'float'; uLayers: 'vec4'; uHero: 'vec4' }> = {
  vertexSrc: `#version 300 es
layout(location = 0) in vec3 aPosition;
layout(location = 1) in vec2 aUv;
layout(location = 2) in vec4 iSlot;
layout(location = 3) in vec4 iRect;
uniform mat4 uViewProj;
uniform sampler2D uMap;
uniform vec2 uMapSize;
uniform sampler2D uLight;
uniform vec2 uAtlasGrid;
uniform vec2 uAtlasInset;
uniform float uTime;
uniform vec4 uLayers;
uniform vec4 uHero;
out vec2 vUv;
out vec4 vTint;
float byteOf(float channel) {
  return floor(channel * 255.0 + 0.5);
}
vec4 atlasRect(float tile, vec2 grid, vec2 inset) {
  float du = 1.0 / grid.x;
  float dv = 1.0 / grid.y;
  float col = mod(tile, grid.x);
  float row = floor(tile / grid.x);
  return vec4(col * du + inset.x, 1.0 - (row + 1.0) * dv + inset.y, du - inset.x * 2.0, dv - inset.y * 2.0);
}
float torchFlicker(float index, float t) {
  return 0.78 + 0.22 * sin(t * (7.0 + index * 1.7) + index * 2.1) * sin(t * 3.1 + index);
}
vec4 patrolPose(vec4 rect, float speed, float t) {
  float lx = rect.z - rect.x;
  float ly = rect.w - rect.y;
  float s = mod(t * speed, max((lx + ly) * 2.0, 1.0));
  float e0 = 1.0 - step(lx, s);
  float e1 = step(lx, s) - step(lx + ly, s);
  float e2 = step(lx + ly, s) - step(lx * 2.0 + ly, s);
  float e3 = step(lx * 2.0 + ly, s);
  float x = e0 * (rect.x + s) + e1 * rect.z + e2 * (rect.z - (s - lx - ly)) + e3 * rect.x;
  float y = e0 * rect.y + e1 * (rect.y + s - lx) + e2 * rect.w + e3 * (rect.w - (s - lx * 2.0 - ly));
  return vec4(x, y + abs(sin(t * 6.0 + x)) * 0.09, mix(1.0, -1.0, e2), y);
}
void main() {
  float role = iSlot.z;
  float wTerrain = 1.0 - step(0.5, role);
  float wProp = step(0.5, role) - step(1.5, role);
  float wFlame = step(1.5, role) - step(2.5, role);
  float wMonster = step(2.5, role) - step(3.5, role);
  float wHero = step(3.5, role);
  float wActor = step(2.5, role);
  vec4 walk = patrolPose(iRect, iSlot.x, uTime);
  float heroY = uHero.y + abs(sin(uTime * 11.0)) * 0.12 * uHero.w;
  vec3 pose = vec3(iSlot.x + 0.5, iSlot.y + 0.5, iSlot.y + 0.5);
  pose = mix(pose, vec3(walk.x, walk.y, walk.w), wMonster);
  pose = mix(pose, vec3(uHero.x, heroY, uHero.y), wHero);
  float facing = mix(1.0, walk.z, wMonster);
  facing = mix(facing, uHero.z, wHero);
  vec2 uv = vec2(pose.x, pose.z) / uMapSize;
  vec4 map = texture(uMap, uv);
  vec4 lit = texture(uLight, uv);
  float kind = byteOf(map.x);
  float fall = max(1.0 - lit.x * lit.x, 0.0);
  float flick = torchFlicker(byteOf(lit.y), uTime);
  vec3 light = vec3(0.3, 0.29, 0.4) + vec3(0.85, 0.5, 0.2) * (fall * fall * flick);
  vec3 albedo = vec3(1.0, 1.0, 1.0) * (wTerrain + wHero) + vec3(0.95, 0.92, 0.88) * wProp + vec3(0.95, 0.95, 1.0) * wMonster;
  vec3 flame = vec3(1.0, 0.85 + flick * 0.15, 0.6 + flick * 0.2);
  vTint = vec4(light * albedo + flame * wFlame, 1.0);
  float tile = mix(byteOf(map.y), iSlot.w, step(0.5, role));
  vec4 rect = atlasRect(tile, uAtlasGrid, uAtlasInset);
  vUv = rect.xy + aUv * rect.zw;
  float actorZ = uLayers.w + (1.0 - pose.z / uMapSize.y) * 0.05;
  float z = wTerrain * mix(uLayers.x, uLayers.y, step(1.5, kind)) + wProp * uLayers.z + wFlame * (uLayers.y + 0.01) + wActor * actorZ;
  vec3 world = vec3(pose.x + aPosition.x * facing, pose.y + aPosition.y, z);
  gl_Position = uViewProj * vec4(world, 1.0);
}
`,
  fragmentSrc: `#version 300 es
precision highp float;
uniform sampler2D uAtlas;
uniform float uCutoff;
in vec2 vUv;
in vec4 vTint;
out vec4 fragColor;
void main() {
  vec4 texel = texture(uAtlas, vUv);
  if (texel.w * vTint.w < uCutoff) {
    discard;
  }
  fragColor = vec4(texel.xyz * vTint.xyz, 1.0);
}
`,
  wgslSrc: `struct BmUniforms {
  uViewProj : mat4x4f,
  uMapSize : vec2f,
  uAtlasGrid : vec2f,
  uAtlasInset : vec2f,
  uTime : f32,
  uCutoff : f32,
  uLayers : vec4f,
  uHero : vec4f,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
@group(0) @binding(1) var uMap : texture_2d<f32>;
@group(0) @binding(2) var uMap_sampler : sampler;
@group(0) @binding(3) var uLight : texture_2d<f32>;
@group(0) @binding(4) var uLight_sampler : sampler;
@group(0) @binding(5) var uAtlas : texture_2d<f32>;
@group(0) @binding(6) var uAtlas_sampler : sampler;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aUv : vec2f,
  @location(2) iSlot : vec4f,
  @location(3) iRect : vec4f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vUv : vec2f,
  @location(1) vTint : vec4f,
}
fn byteOf(channel : f32) -> f32 {
  return floor(channel * 255.0 + 0.5);
}
fn atlasRect(tile : f32, grid : vec2f, inset : vec2f) -> vec4f {
  let du = 1.0 / grid.x;
  let dv = 1.0 / grid.y;
  let col = ((tile) - (grid.x) * floor((tile) / (grid.x)));
  let row = floor(tile / grid.x);
  return vec4f(col * du + inset.x, 1.0 - (row + 1.0) * dv + inset.y, du - inset.x * 2.0, dv - inset.y * 2.0);
}
fn torchFlicker(index : f32, t : f32) -> f32 {
  return 0.78 + 0.22 * sin(t * (7.0 + index * 1.7) + index * 2.1) * sin(t * 3.1 + index);
}
fn patrolPose(rect : vec4f, speed : f32, t : f32) -> vec4f {
  let lx = rect.z - rect.x;
  let ly = rect.w - rect.y;
  let s = ((t * speed) - (max((lx + ly) * 2.0, 1.0)) * floor((t * speed) / (max((lx + ly) * 2.0, 1.0))));
  let e0 = 1.0 - step(lx, s);
  let e1 = step(lx, s) - step(lx + ly, s);
  let e2 = step(lx + ly, s) - step(lx * 2.0 + ly, s);
  let e3 = step(lx * 2.0 + ly, s);
  let x = e0 * (rect.x + s) + e1 * rect.z + e2 * (rect.z - (s - lx - ly)) + e3 * rect.x;
  let y = e0 * rect.y + e1 * (rect.y + s - lx) + e2 * rect.w + e3 * (rect.w - (s - lx * 2.0 - ly));
  return vec4f(x, y + abs(sin(t * 6.0 + x)) * 0.09, mix(1.0, -1.0, e2), y);
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  let role = bm_in.iSlot.z;
  let wTerrain = 1.0 - step(0.5, role);
  let wProp = step(0.5, role) - step(1.5, role);
  let wFlame = step(1.5, role) - step(2.5, role);
  let wMonster = step(2.5, role) - step(3.5, role);
  let wHero = step(3.5, role);
  let wActor = step(2.5, role);
  let walk = patrolPose(bm_in.iRect, bm_in.iSlot.x, bm_u.uTime);
  let heroY = bm_u.uHero.y + abs(sin(bm_u.uTime * 11.0)) * 0.12 * bm_u.uHero.w;
  var pose = vec3f(bm_in.iSlot.x + 0.5, bm_in.iSlot.y + 0.5, bm_in.iSlot.y + 0.5);
  pose = mix(pose, vec3f(walk.x, walk.y, walk.w), wMonster);
  pose = mix(pose, vec3f(bm_u.uHero.x, heroY, bm_u.uHero.y), wHero);
  var facing = mix(1.0, walk.z, wMonster);
  facing = mix(facing, bm_u.uHero.z, wHero);
  let uv = vec2f(pose.x, pose.z) / bm_u.uMapSize;
  let map = textureSampleLevel(uMap, uMap_sampler, uv, 0.0);
  let lit = textureSampleLevel(uLight, uLight_sampler, uv, 0.0);
  let kind = byteOf(map.x);
  let fall = max(1.0 - lit.x * lit.x, 0.0);
  let flick = torchFlicker(byteOf(lit.y), bm_u.uTime);
  let light = vec3f(0.3, 0.29, 0.4) + vec3f(0.85, 0.5, 0.2) * (fall * fall * flick);
  let albedo = vec3f(1.0, 1.0, 1.0) * (wTerrain + wHero) + vec3f(0.95, 0.92, 0.88) * wProp + vec3f(0.95, 0.95, 1.0) * wMonster;
  let flame = vec3f(1.0, 0.85 + flick * 0.15, 0.6 + flick * 0.2);
  bm_out.vTint = vec4f(light * albedo + flame * wFlame, 1.0);
  let tile = mix(byteOf(map.y), bm_in.iSlot.w, step(0.5, role));
  let rect = atlasRect(tile, bm_u.uAtlasGrid, bm_u.uAtlasInset);
  bm_out.vUv = rect.xy + bm_in.aUv * rect.zw;
  let actorZ = bm_u.uLayers.w + (1.0 - pose.z / bm_u.uMapSize.y) * 0.05;
  let z = wTerrain * mix(bm_u.uLayers.x, bm_u.uLayers.y, step(1.5, kind)) + wProp * bm_u.uLayers.z + wFlame * (bm_u.uLayers.y + 0.01) + wActor * actorZ;
  let world = vec3f(pose.x + bm_in.aPosition.x * facing, pose.y + bm_in.aPosition.y, z);
  bm_out.bm_position = bm_u.uViewProj * vec4f(world, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let texel = textureSample(uAtlas, uAtlas_sampler, bm_in.vUv);
  if (texel.w * bm_in.vTint.w < bm_u.uCutoff) {
    discard;
  }
  return vec4f(texel.xyz * bm_in.vTint.xyz, 1.0);
}
`,
  attributes: { aPosition: 'vec3', aUv: 'vec2' },
  instanceAttributes: { iSlot: 'vec4', iRect: 'vec4' },
  uniforms: { uViewProj: 'mat4', uMap: 'sampler2D', uMapSize: 'vec2', uLight: 'sampler2D', uAtlas: 'sampler2D', uAtlasGrid: 'vec2', uAtlasInset: 'vec2', uTime: 'float', uCutoff: 'float', uLayers: 'vec4', uHero: 'vec4' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aUv","type":"vec2","location":1,"size":2,"divisor":0},{"name":"iSlot","type":"vec4","location":2,"size":4,"divisor":1},{"name":"iRect","type":"vec4","location":3,"size":4,"divisor":1}],"uniforms":[{"name":"uViewProj","type":"mat4","kind":"m4fv","size":16,"offset":0},{"name":"uMap","type":"sampler2D","kind":"1i","size":1,"unit":0,"textureBinding":1,"samplerBinding":2},{"name":"uMapSize","type":"vec2","kind":"2fv","size":2,"offset":64},{"name":"uLight","type":"sampler2D","kind":"1i","size":1,"unit":1,"textureBinding":3,"samplerBinding":4},{"name":"uAtlas","type":"sampler2D","kind":"1i","size":1,"unit":2,"textureBinding":5,"samplerBinding":6},{"name":"uAtlasGrid","type":"vec2","kind":"2fv","size":2,"offset":72},{"name":"uAtlasInset","type":"vec2","kind":"2fv","size":2,"offset":80},{"name":"uTime","type":"float","kind":"1f","size":1,"offset":88},{"name":"uCutoff","type":"float","kind":"1f","size":1,"offset":92},{"name":"uLayers","type":"vec4","kind":"4fv","size":4,"offset":96},{"name":"uHero","type":"vec4","kind":"4fv","size":4,"offset":112}],"uniformBlockSize":128},
};

export default topdownDungeonShader;
