/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const worldWaterShader: CompiledShader<{ aPosition: 'vec3' }, Record<string, never>, { uViewProj: 'mat4'; uCamPos: 'vec3'; uLightDir: 'vec3'; uTime: 'float'; uWaterLevel: 'float' }> = {
  vertexSrc: `#version 300 es
layout(location = 0) in vec3 aPosition;
uniform mat4 uViewProj;
uniform vec3 uCamPos;
uniform float uTime;
uniform float uWaterLevel;
out vec3 vWorld;
out float vDepth;
out float vBed;
out float vWave;
float terrainHeight(float x, float z) {
  return 1.55 * sin(x * 0.085) * cos(z * 0.075) + 0.75 * sin(x * 0.17 + 1.7) * cos(z * 0.155 + 0.6) + 0.35 * sin((x + z) * 0.26 + 2.4);
}
float waveHeight(float x, float z, float t) {
  return sin(x * 0.55 + t * 1.15) * 0.55 + sin(z * 0.42 - t * 0.85) * 0.3 + sin((x + z) * 0.9 + t * 1.9) * 0.15;
}
void main() {
  float wave = waveHeight(aPosition.x, aPosition.z, uTime);
  vec3 world = vec3(aPosition.x, uWaterLevel + wave * 0.055, aPosition.z);
  float bed = uWaterLevel - terrainHeight(aPosition.x, aPosition.z);
  vWorld = world;
  vWave = wave;
  vBed = bed;
  vDepth = length(world - uCamPos);
  vec4 clip = uViewProj * vec4(world, 1.0);
  if (bed < -0.5) {
    clip = vec4(2.0, 2.0, 2.0, 1.0);
  }
  gl_Position = clip;
}
`,
  fragmentSrc: `#version 300 es
precision highp float;
uniform vec3 uCamPos;
uniform vec3 uLightDir;
uniform float uTime;
in vec3 vWorld;
in float vDepth;
in float vBed;
in float vWave;
out vec4 fragColor;
vec3 waveNormal(float x, float z, float t) {
  float cosA = cos(x * 0.55 + t * 1.15);
  float cosB = cos(z * 0.42 - t * 0.85);
  float cosC = cos((x + z) * 0.9 + t * 1.9);
  float gx = 0.55 * 0.55 * cosA + 0.15 * 0.9 * cosC;
  float gz = 0.3 * 0.42 * cosB + 0.15 * 0.9 * cosC;
  return normalize(vec3(-gx * 0.154, 1.0, -gz * 0.154));
}
void main() {
  vec3 normal = waveNormal(vWorld.x, vWorld.z, uTime);
  vec3 shallow = vec3(0.42, 0.75, 0.72);
  vec3 deep = vec3(0.07, 0.24, 0.42);
  vec3 body = mix(shallow, deep, smoothstep(0.05, 2.6, vBed));
  vec3 view = normalize(uCamPos - vWorld);
  vec3 light = normalize(uLightDir);
  float fresnel = pow(1.0 - max(dot(normal, view), 0.0), 3.0);
  float spec = pow(max(dot(reflect(light * -1.0, normal), view), 0.0), 48.0);
  vec3 sky = vec3(0.62, 0.79, 0.9);
  vec3 color = mix(body, sky, fresnel * 0.6);
  color = color + vec3(1.0, 0.98, 0.9) * (spec * 0.55);
  float shoreFoam = 1.0 - smoothstep(0.02, 0.34, vBed);
  float crestFoam = smoothstep(0.72, 0.98, vWave) * 0.35;
  color = mix(color, vec3(0.93, 0.97, 0.98), max(shoreFoam, crestFoam));
  fragColor = vec4(color, vDepth);
}
`,
  wgslSrc: `struct BmUniforms {
  uViewProj : mat4x4f,
  uCamPos : vec3f,
  uLightDir : vec3f,
  uTime : f32,
  uWaterLevel : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
struct BmVSIn {
  @location(0) aPosition : vec3f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vWorld : vec3f,
  @location(1) vDepth : f32,
  @location(2) vBed : f32,
  @location(3) vWave : f32,
}
fn terrainHeight(x : f32, z : f32) -> f32 {
  return 1.55 * sin(x * 0.085) * cos(z * 0.075) + 0.75 * sin(x * 0.17 + 1.7) * cos(z * 0.155 + 0.6) + 0.35 * sin((x + z) * 0.26 + 2.4);
}
fn waveHeight(x : f32, z : f32, t : f32) -> f32 {
  return sin(x * 0.55 + t * 1.15) * 0.55 + sin(z * 0.42 - t * 0.85) * 0.3 + sin((x + z) * 0.9 + t * 1.9) * 0.15;
}
fn waveNormal(x : f32, z : f32, t : f32) -> vec3f {
  let cosA = cos(x * 0.55 + t * 1.15);
  let cosB = cos(z * 0.42 - t * 0.85);
  let cosC = cos((x + z) * 0.9 + t * 1.9);
  let gx = 0.55 * 0.55 * cosA + 0.15 * 0.9 * cosC;
  let gz = 0.3 * 0.42 * cosB + 0.15 * 0.9 * cosC;
  return normalize(vec3f(-gx * 0.154, 1.0, -gz * 0.154));
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  let wave = waveHeight(bm_in.aPosition.x, bm_in.aPosition.z, bm_u.uTime);
  let world = vec3f(bm_in.aPosition.x, bm_u.uWaterLevel + wave * 0.055, bm_in.aPosition.z);
  let bed = bm_u.uWaterLevel - terrainHeight(bm_in.aPosition.x, bm_in.aPosition.z);
  bm_out.vWorld = world;
  bm_out.vWave = wave;
  bm_out.vBed = bed;
  bm_out.vDepth = length(world - bm_u.uCamPos);
  var clip = bm_u.uViewProj * vec4f(world, 1.0);
  if (bed < -0.5) {
    clip = vec4f(2.0, 2.0, 2.0, 1.0);
  }
  bm_out.bm_position = clip;
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let normal = waveNormal(bm_in.vWorld.x, bm_in.vWorld.z, bm_u.uTime);
  let shallow = vec3f(0.42, 0.75, 0.72);
  let deep = vec3f(0.07, 0.24, 0.42);
  let body = mix(shallow, deep, smoothstep(0.05, 2.6, bm_in.vBed));
  let view = normalize(bm_u.uCamPos - bm_in.vWorld);
  let light = normalize(bm_u.uLightDir);
  let fresnel = pow(1.0 - max(dot(normal, view), 0.0), 3.0);
  let spec = pow(max(dot(reflect(light * -1.0, normal), view), 0.0), 48.0);
  let sky = vec3f(0.62, 0.79, 0.9);
  var color = mix(body, sky, fresnel * 0.6);
  color = color + vec3f(1.0, 0.98, 0.9) * (spec * 0.55);
  let shoreFoam = 1.0 - smoothstep(0.02, 0.34, bm_in.vBed);
  let crestFoam = smoothstep(0.72, 0.98, bm_in.vWave) * 0.35;
  color = mix(color, vec3f(0.93, 0.97, 0.98), max(shoreFoam, crestFoam));
  return vec4f(color, bm_in.vDepth);
}
`,
  attributes: { aPosition: 'vec3' },
  instanceAttributes: {},
  uniforms: { uViewProj: 'mat4', uCamPos: 'vec3', uLightDir: 'vec3', uTime: 'float', uWaterLevel: 'float' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0}],"uniforms":[{"name":"uViewProj","type":"mat4","kind":"m4fv","size":16,"offset":0},{"name":"uCamPos","type":"vec3","kind":"3fv","size":3,"offset":64},{"name":"uLightDir","type":"vec3","kind":"3fv","size":3,"offset":80},{"name":"uTime","type":"float","kind":"1f","size":1,"offset":92},{"name":"uWaterLevel","type":"float","kind":"1f","size":1,"offset":96}],"uniformBlockSize":112},
};

export default worldWaterShader;
