/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const worldPostShader: CompiledShader<{ aPosition: 'vec3' }, Record<string, never>, { uScene: 'sampler2D'; uTexel: 'vec2'; uFocus: 'float'; uAperture: 'float'; uFocusRange: 'float'; uVignette: 'float' }> = {
  vertexSrc: `#version 300 es
layout(location = 0) in vec3 aPosition;
out vec2 vUv;
void main() {
  vUv = ((vec4(aPosition.x, aPosition.y, 0.0, 1.0)).xy / (vec4(aPosition.x, aPosition.y, 0.0, 1.0)).w * 0.5 + 0.5);
  gl_Position = vec4(aPosition.x, aPosition.y, 0.0, 1.0);
}
`,
  fragmentSrc: `#version 300 es
precision highp float;
uniform sampler2D uScene;
uniform vec2 uTexel;
uniform float uFocus;
uniform float uAperture;
uniform float uFocusRange;
uniform float uVignette;
in vec2 vUv;
out vec4 fragColor;
void main() {
  vec4 center = texture(uScene, vUv);
  float depth = center.w;
  float coc = clamp(abs(depth - uFocus) / max(uFocusRange, 0.001), 0.0, 1.0);
  float radius = coc * uAperture;
  vec3 sum = vec3(center.x, center.y, center.z);
  float weight = 1.0;
  for (float i = 0.0; i < 16.0; i = i + 1.0) {
    float angle = i * 2.39996;
    float spread = sqrt((i + 0.5) / 16.0);
    vec2 offset = vec2(cos(angle), sin(angle)) * (spread * radius);
    vec2 uv = vUv + offset * uTexel;
    vec4 tap = texture(uScene, uv);
    float tapCoc = clamp(abs(tap.w - uFocus) / max(uFocusRange, 0.001), 0.0, 1.0);
    float admit = smoothstep(coc * 0.35, coc * 0.9 + 0.05, tapCoc + 0.02);
    sum = sum + vec3(tap.x, tap.y, tap.z) * admit;
    weight = weight + admit;
  }
  vec3 color = sum * (1.0 / weight);
  float r = length(vUv - vec2(0.5, 0.5)) * 1.41421;
  float shade = 1.0 - uVignette * smoothstep(0.35, 1.05, r);
  color = mix(color * shade, color * shade * vec3(0.9, 0.93, 1.0), uVignette * 0.5);
  fragColor = vec4(color, 1.0);
}
`,
  wgslSrc: `struct BmUniforms {
  uTexel : vec2f,
  uFocus : f32,
  uAperture : f32,
  uFocusRange : f32,
  uVignette : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
@group(0) @binding(1) var uScene : texture_2d<f32>;
@group(0) @binding(2) var uScene_sampler : sampler;
struct BmVSIn {
  @location(0) aPosition : vec3f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vUv : vec2f,
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  bm_out.vUv = ((vec4f(bm_in.aPosition.x, bm_in.aPosition.y, 0.0, 1.0)).xy / (vec4f(bm_in.aPosition.x, bm_in.aPosition.y, 0.0, 1.0)).w * vec2f(0.5, -0.5) + vec2f(0.5));
  bm_out.bm_position = vec4f(bm_in.aPosition.x, bm_in.aPosition.y, 0.0, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let center = textureSample(uScene, uScene_sampler, bm_in.vUv);
  let depth = center.w;
  let coc = clamp(abs(depth - bm_u.uFocus) / max(bm_u.uFocusRange, 0.001), 0.0, 1.0);
  let radius = coc * bm_u.uAperture;
  var sum = vec3f(center.x, center.y, center.z);
  var weight = 1.0;
  for (var i = 0.0; i < 16.0; i = i + 1.0) {
    let angle = i * 2.39996;
    let spread = sqrt((i + 0.5) / 16.0);
    let offset = vec2f(cos(angle), sin(angle)) * (spread * radius);
    let uv = bm_in.vUv + offset * bm_u.uTexel;
    let tap = textureSample(uScene, uScene_sampler, uv);
    let tapCoc = clamp(abs(tap.w - bm_u.uFocus) / max(bm_u.uFocusRange, 0.001), 0.0, 1.0);
    let admit = smoothstep(coc * 0.35, coc * 0.9 + 0.05, tapCoc + 0.02);
    sum = sum + vec3f(tap.x, tap.y, tap.z) * admit;
    weight = weight + admit;
  }
  var color = sum * (1.0 / weight);
  let r = length(bm_in.vUv - vec2f(0.5, 0.5)) * 1.41421;
  let shade = 1.0 - bm_u.uVignette * smoothstep(0.35, 1.05, r);
  color = mix(color * shade, color * shade * vec3f(0.9, 0.93, 1.0), bm_u.uVignette * 0.5);
  return vec4f(color, 1.0);
}
`,
  attributes: { aPosition: 'vec3' },
  instanceAttributes: {},
  uniforms: { uScene: 'sampler2D', uTexel: 'vec2', uFocus: 'float', uAperture: 'float', uFocusRange: 'float', uVignette: 'float' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0}],"uniforms":[{"name":"uScene","type":"sampler2D","kind":"1i","size":1,"unit":0,"textureBinding":1,"samplerBinding":2},{"name":"uTexel","type":"vec2","kind":"2fv","size":2,"offset":0},{"name":"uFocus","type":"float","kind":"1f","size":1,"offset":8},{"name":"uAperture","type":"float","kind":"1f","size":1,"offset":12},{"name":"uFocusRange","type":"float","kind":"1f","size":1,"offset":16},{"name":"uVignette","type":"float","kind":"1f","size":1,"offset":20}],"uniformBlockSize":32},
};

export default worldPostShader;
