/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const worldGroundShader: CompiledShader<{ aPosition: 'vec3' }, Record<string, never>, { uViewProj: 'mat4'; uCamPos: 'vec3'; uLightDir: 'vec3'; uWaterLevel: 'float' }> = {
  vertexSrc: `#version 300 es
layout(location = 0) in vec3 aPosition;
uniform mat4 uViewProj;
uniform vec3 uCamPos;
out vec3 vNormal;
out float vHeight;
out float vDepth;
out float vSlope;
vec3 terrainField(float x, float z) {
  float sinAx = sin(x * 0.085);
  float cosAx = cos(x * 0.085);
  float sinAz = sin(z * 0.075);
  float cosAz = cos(z * 0.075);
  float sinBx = sin(x * 0.17 + 1.7);
  float cosBx = cos(x * 0.17 + 1.7);
  float sinBz = sin(z * 0.155 + 0.6);
  float cosBz = cos(z * 0.155 + 0.6);
  float sinC = sin((x + z) * 0.26 + 2.4);
  float cosC = cos((x + z) * 0.26 + 2.4);
  return vec3(1.55 * sinAx * cosAz + 0.75 * sinBx * cosBz + 0.35 * sinC, 1.55 * 0.085 * cosAx * cosAz + 0.75 * 0.17 * cosBx * cosBz + 0.35 * 0.26 * cosC, -1.55 * 0.075 * sinAx * sinAz - 0.75 * 0.155 * sinBx * sinBz + 0.35 * 0.26 * cosC);
}
void main() {
  vec3 field = terrainField(aPosition.x, aPosition.z);
  vec3 world = vec3(aPosition.x, field.x, aPosition.z);
  vNormal = normalize(vec3(-field.y, 1.0, -field.z));
  vSlope = length(vec2(field.y, field.z));
  vHeight = field.x;
  vDepth = length(world - uCamPos);
  gl_Position = uViewProj * vec4(world, 1.0);
}
`,
  fragmentSrc: `#version 300 es
precision highp float;
uniform vec3 uLightDir;
uniform float uWaterLevel;
in vec3 vNormal;
in float vHeight;
in float vDepth;
in float vSlope;
out vec4 fragColor;
void main() {
  vec3 normal = normalize(vNormal);
  float diffuse = max(dot(normal, normalize(uLightDir)), 0.0);
  float ambient = 0.6 + 0.16 * max(-normal.y, 0.0);
  vec3 sand = vec3(0.79, 0.71, 0.48);
  vec3 grass = vec3(0.29, 0.5, 0.24);
  vec3 grassDry = vec3(0.44, 0.55, 0.26);
  vec3 rock = vec3(0.44, 0.42, 0.42);
  float shore = 1.0 - smoothstep(uWaterLevel - 0.1, uWaterLevel + 0.55, vHeight);
  float dry = smoothstep(0.1, 1.3, vHeight);
  vec3 albedo = mix(grass, grassDry, dry);
  albedo = mix(albedo, rock, smoothstep(0.22, 0.29, vSlope));
  albedo = mix(albedo, sand, shore);
  fragColor = vec4(albedo * (ambient + diffuse * 0.62), vDepth);
}
`,
  wgslSrc: `struct BmUniforms {
  uViewProj : mat4x4f,
  uCamPos : vec3f,
  uLightDir : vec3f,
  uWaterLevel : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
struct BmVSIn {
  @location(0) aPosition : vec3f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vNormal : vec3f,
  @location(1) vHeight : f32,
  @location(2) vDepth : f32,
  @location(3) vSlope : f32,
}
fn terrainField(x : f32, z : f32) -> vec3f {
  let sinAx = sin(x * 0.085);
  let cosAx = cos(x * 0.085);
  let sinAz = sin(z * 0.075);
  let cosAz = cos(z * 0.075);
  let sinBx = sin(x * 0.17 + 1.7);
  let cosBx = cos(x * 0.17 + 1.7);
  let sinBz = sin(z * 0.155 + 0.6);
  let cosBz = cos(z * 0.155 + 0.6);
  let sinC = sin((x + z) * 0.26 + 2.4);
  let cosC = cos((x + z) * 0.26 + 2.4);
  return vec3f(1.55 * sinAx * cosAz + 0.75 * sinBx * cosBz + 0.35 * sinC, 1.55 * 0.085 * cosAx * cosAz + 0.75 * 0.17 * cosBx * cosBz + 0.35 * 0.26 * cosC, -1.55 * 0.075 * sinAx * sinAz - 0.75 * 0.155 * sinBx * sinBz + 0.35 * 0.26 * cosC);
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  let field = terrainField(bm_in.aPosition.x, bm_in.aPosition.z);
  let world = vec3f(bm_in.aPosition.x, field.x, bm_in.aPosition.z);
  bm_out.vNormal = normalize(vec3f(-field.y, 1.0, -field.z));
  bm_out.vSlope = length(vec2f(field.y, field.z));
  bm_out.vHeight = field.x;
  bm_out.vDepth = length(world - bm_u.uCamPos);
  bm_out.bm_position = bm_u.uViewProj * vec4f(world, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let normal = normalize(bm_in.vNormal);
  let diffuse = max(dot(normal, normalize(bm_u.uLightDir)), 0.0);
  let ambient = 0.6 + 0.16 * max(-normal.y, 0.0);
  let sand = vec3f(0.79, 0.71, 0.48);
  let grass = vec3f(0.29, 0.5, 0.24);
  let grassDry = vec3f(0.44, 0.55, 0.26);
  let rock = vec3f(0.44, 0.42, 0.42);
  let shore = 1.0 - smoothstep(bm_u.uWaterLevel - 0.1, bm_u.uWaterLevel + 0.55, bm_in.vHeight);
  let dry = smoothstep(0.1, 1.3, bm_in.vHeight);
  var albedo = mix(grass, grassDry, dry);
  albedo = mix(albedo, rock, smoothstep(0.22, 0.29, bm_in.vSlope));
  albedo = mix(albedo, sand, shore);
  return vec4f(albedo * (ambient + diffuse * 0.62), bm_in.vDepth);
}
`,
  attributes: { aPosition: 'vec3' },
  instanceAttributes: {},
  uniforms: { uViewProj: 'mat4', uCamPos: 'vec3', uLightDir: 'vec3', uWaterLevel: 'float' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0}],"uniforms":[{"name":"uViewProj","type":"mat4","kind":"m4fv","size":16,"offset":0},{"name":"uCamPos","type":"vec3","kind":"3fv","size":3,"offset":64},{"name":"uLightDir","type":"vec3","kind":"3fv","size":3,"offset":80},{"name":"uWaterLevel","type":"float","kind":"1f","size":1,"offset":92}],"uniformBlockSize":96},
};

export default worldGroundShader;
