/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const worldGrassShader: CompiledShader<{ aPosition: 'vec3'; aNormal: 'vec3'; aColor: 'vec3' }, { iPos: 'vec3'; iScaleRot: 'vec3'; iTint: 'vec3' }, { uViewProj: 'mat4'; uCamPos: 'vec3'; uLightDir: 'vec3'; uTime: 'float'; uWind: 'float' }> = {
  vertexSrc: `#version 300 es
layout(location = 0) in vec3 aPosition;
layout(location = 1) in vec3 aNormal;
layout(location = 2) in vec3 aColor;
layout(location = 3) in vec3 iPos;
layout(location = 4) in vec3 iScaleRot;
layout(location = 5) in vec3 iTint;
uniform mat4 uViewProj;
uniform vec3 uCamPos;
uniform vec3 uLightDir;
uniform float uTime;
uniform float uWind;
out vec3 vColor;
out float vDepth;
out float vShade;
void main() {
  float phase = uTime * 1.9 + iPos.x * 0.55 + iPos.z * 0.4;
  float gust = sin(phase) * 0.6 + sin(phase * 0.41 + 1.3) * 0.4;
  float bend = gust * uWind * aPosition.y * aPosition.y;
  float c = iScaleRot.y;
  float sn = iScaleRot.z;
  vec3 bent = vec3(aPosition.x + bend, aPosition.y - bend * bend * 0.35, aPosition.z);
  vec3 rotated = vec3(bent.x * c + bent.z * sn, bent.y, bent.z * c - bent.x * sn);
  vec3 world = rotated * iScaleRot.x + iPos;
  vec3 normal = normalize(vec3(aNormal.x * c + aNormal.z * sn, aNormal.y, aNormal.z * c - aNormal.x * sn));
  vShade = 0.45 + max(dot(normal, normalize(uLightDir)), 0.0) * 0.55;
  vColor = aColor * iTint;
  vDepth = length(world - uCamPos);
  gl_Position = uViewProj * vec4(world, 1.0);
}
`,
  fragmentSrc: `#version 300 es
precision highp float;
in vec3 vColor;
in float vDepth;
in float vShade;
out vec4 fragColor;
void main() {
  fragColor = vec4(vColor * vShade, vDepth);
}
`,
  wgslSrc: `struct BmUniforms {
  uViewProj : mat4x4f,
  uCamPos : vec3f,
  uLightDir : vec3f,
  uTime : f32,
  uWind : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aNormal : vec3f,
  @location(2) aColor : vec3f,
  @location(3) iPos : vec3f,
  @location(4) iScaleRot : vec3f,
  @location(5) iTint : vec3f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vColor : vec3f,
  @location(1) vDepth : f32,
  @location(2) vShade : f32,
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  let phase = bm_u.uTime * 1.9 + bm_in.iPos.x * 0.55 + bm_in.iPos.z * 0.4;
  let gust = sin(phase) * 0.6 + sin(phase * 0.41 + 1.3) * 0.4;
  let bend = gust * bm_u.uWind * bm_in.aPosition.y * bm_in.aPosition.y;
  let c = bm_in.iScaleRot.y;
  let sn = bm_in.iScaleRot.z;
  let bent = vec3f(bm_in.aPosition.x + bend, bm_in.aPosition.y - bend * bend * 0.35, bm_in.aPosition.z);
  let rotated = vec3f(bent.x * c + bent.z * sn, bent.y, bent.z * c - bent.x * sn);
  let world = rotated * bm_in.iScaleRot.x + bm_in.iPos;
  let normal = normalize(vec3f(bm_in.aNormal.x * c + bm_in.aNormal.z * sn, bm_in.aNormal.y, bm_in.aNormal.z * c - bm_in.aNormal.x * sn));
  bm_out.vShade = 0.45 + max(dot(normal, normalize(bm_u.uLightDir)), 0.0) * 0.55;
  bm_out.vColor = bm_in.aColor * bm_in.iTint;
  bm_out.vDepth = length(world - bm_u.uCamPos);
  bm_out.bm_position = bm_u.uViewProj * vec4f(world, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  return vec4f(bm_in.vColor * bm_in.vShade, bm_in.vDepth);
}
`,
  attributes: { aPosition: 'vec3', aNormal: 'vec3', aColor: 'vec3' },
  instanceAttributes: { iPos: 'vec3', iScaleRot: 'vec3', iTint: 'vec3' },
  uniforms: { uViewProj: 'mat4', uCamPos: 'vec3', uLightDir: 'vec3', uTime: 'float', uWind: 'float' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aNormal","type":"vec3","location":1,"size":3,"divisor":0},{"name":"aColor","type":"vec3","location":2,"size":3,"divisor":0},{"name":"iPos","type":"vec3","location":3,"size":3,"divisor":1},{"name":"iScaleRot","type":"vec3","location":4,"size":3,"divisor":1},{"name":"iTint","type":"vec3","location":5,"size":3,"divisor":1}],"uniforms":[{"name":"uViewProj","type":"mat4","kind":"m4fv","size":16,"offset":0},{"name":"uCamPos","type":"vec3","kind":"3fv","size":3,"offset":64},{"name":"uLightDir","type":"vec3","kind":"3fv","size":3,"offset":80},{"name":"uTime","type":"float","kind":"1f","size":1,"offset":92},{"name":"uWind","type":"float","kind":"1f","size":1,"offset":96}],"uniformBlockSize":112},
};

export default worldGrassShader;
