/* Generated by BroMetal. Do not edit — recompile with `npx brometal dev`. */
import type { CompiledShader } from 'brometal';

const worldSpriteShader: CompiledShader<{ aPosition: 'vec3'; aUv: 'vec2' }, { iCenter: 'vec3'; iSize: 'vec2'; iUvRect: 'vec4'; iTint: 'vec4' }, { uViewProj: 'mat4'; uRight: 'vec3'; uUp: 'vec3'; uCamPos: 'vec3'; uAtlas: 'sampler2D'; uCutoff: 'float' }> = {
  vertexSrc: `#version 300 es
layout(location = 0) in vec3 aPosition;
layout(location = 1) in vec2 aUv;
layout(location = 2) in vec3 iCenter;
layout(location = 3) in vec2 iSize;
layout(location = 4) in vec4 iUvRect;
layout(location = 5) in vec4 iTint;
uniform mat4 uViewProj;
uniform vec3 uRight;
uniform vec3 uUp;
uniform vec3 uCamPos;
out vec2 vUv;
out vec4 vTint;
out float vDepth;
void main() {
  vec3 world = iCenter + uRight * (aPosition.x * iSize.x) + uUp * (aPosition.y * iSize.y);
  vUv = iUvRect.xy + aUv * iUvRect.zw;
  vTint = iTint;
  vDepth = length(world - uCamPos);
  gl_Position = uViewProj * vec4(world, 1.0);
}
`,
  fragmentSrc: `#version 300 es
precision highp float;
uniform sampler2D uAtlas;
uniform float uCutoff;
in vec2 vUv;
in vec4 vTint;
in float vDepth;
out vec4 fragColor;
void main() {
  vec4 texel = texture(uAtlas, vUv);
  if (texel.w * vTint.w < uCutoff) {
    discard;
  }
  vec3 lit = texel.xyz * vTint.xyz;
  fragColor = vec4(lit, vDepth);
}
`,
  wgslSrc: `struct BmUniforms {
  uViewProj : mat4x4f,
  uRight : vec3f,
  uUp : vec3f,
  uCamPos : vec3f,
  uCutoff : f32,
}
@group(0) @binding(0) var<uniform> bm_u : BmUniforms;
@group(0) @binding(1) var uAtlas : texture_2d<f32>;
@group(0) @binding(2) var uAtlas_sampler : sampler;
struct BmVSIn {
  @location(0) aPosition : vec3f,
  @location(1) aUv : vec2f,
  @location(2) iCenter : vec3f,
  @location(3) iSize : vec2f,
  @location(4) iUvRect : vec4f,
  @location(5) iTint : vec4f,
}
struct BmVSOut {
  @builtin(position) bm_position : vec4f,
  @location(0) vUv : vec2f,
  @location(1) vTint : vec4f,
  @location(2) vDepth : f32,
}
@vertex
fn vs_main(bm_in : BmVSIn) -> BmVSOut {
  var bm_out : BmVSOut;
  let world = bm_in.iCenter + bm_u.uRight * (bm_in.aPosition.x * bm_in.iSize.x) + bm_u.uUp * (bm_in.aPosition.y * bm_in.iSize.y);
  bm_out.vUv = bm_in.iUvRect.xy + bm_in.aUv * bm_in.iUvRect.zw;
  bm_out.vTint = bm_in.iTint;
  bm_out.vDepth = length(world - bm_u.uCamPos);
  bm_out.bm_position = bm_u.uViewProj * vec4f(world, 1.0);
  bm_out.bm_position.z = (bm_out.bm_position.z + bm_out.bm_position.w) * 0.5;
  return bm_out;
}
@fragment
fn fs_main(bm_in : BmVSOut) -> @location(0) vec4f {
  let texel = textureSample(uAtlas, uAtlas_sampler, bm_in.vUv);
  if (texel.w * bm_in.vTint.w < bm_u.uCutoff) {
    discard;
  }
  let lit = texel.xyz * bm_in.vTint.xyz;
  return vec4f(lit, bm_in.vDepth);
}
`,
  attributes: { aPosition: 'vec3', aUv: 'vec2' },
  instanceAttributes: { iCenter: 'vec3', iSize: 'vec2', iUvRect: 'vec4', iTint: 'vec4' },
  uniforms: { uViewProj: 'mat4', uRight: 'vec3', uUp: 'vec3', uCamPos: 'vec3', uAtlas: 'sampler2D', uCutoff: 'float' },
  layout: {"attributes":[{"name":"aPosition","type":"vec3","location":0,"size":3,"divisor":0},{"name":"aUv","type":"vec2","location":1,"size":2,"divisor":0},{"name":"iCenter","type":"vec3","location":2,"size":3,"divisor":1},{"name":"iSize","type":"vec2","location":3,"size":2,"divisor":1},{"name":"iUvRect","type":"vec4","location":4,"size":4,"divisor":1},{"name":"iTint","type":"vec4","location":5,"size":4,"divisor":1}],"uniforms":[{"name":"uViewProj","type":"mat4","kind":"m4fv","size":16,"offset":0},{"name":"uRight","type":"vec3","kind":"3fv","size":3,"offset":64},{"name":"uUp","type":"vec3","kind":"3fv","size":3,"offset":80},{"name":"uCamPos","type":"vec3","kind":"3fv","size":3,"offset":96},{"name":"uAtlas","type":"sampler2D","kind":"1i","size":1,"unit":0,"textureBinding":1,"samplerBinding":2},{"name":"uCutoff","type":"float","kind":"1f","size":1,"offset":108}],"uniformBlockSize":112},
};

export default worldSpriteShader;
